[tool.poetry]
name = "tcup"
version = "0.1.0"
description = ""
authors = ["William Martin <30499074+wm1995@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
arviz = "^0.14.0"

[tool.poetry.group.numpyro.dependencies]
numpyro = "^0.10.1"

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"
flake8 = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
