[tool.poetry]
name = "tcup"
version = "0.1.0"
description = ""
authors = ["William Martin <30499074+wm1995@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pystan = "^3.6.0"
arviz = "^0.14.0"
tensorflow-probability = {extras = ["jax"], version = "^0.19.0"}
xdgmm = {git = "https://github.com/wm1995/XDGMM.git", rev = "ported"}

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"
flake8 = "^6.0.0"
pytest = "^7.2.0"

[tool.black]
line-length = 79

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
