name: Pull request CI
on: [pull_request]
jobs:
    python-lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: chartboost/ruff-action@v1
    python-format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: chartboost/ruff-action@v1
              with:
                args: 'format --check'
    pytest:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.10'
            - run: |
                pip install poetry==1.3.1
                poetry lock
                poetry install --all-extras --with dev
            - run: poetry run pytest tests/
            - uses: stefanzweifel/git-auto-commit-action@v5
              with:
                commit_message: Update poetry lockfile
