name: Pull request CI
on: [pull_request]
jobs:
    python-lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: chartboost/ruff-action@v1
    python-format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: chartboost/ruff-action@v1
              with:
                args: 'format --check'
    pytest:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                submodules: true
            - uses: actions/setup-python@v5
              with:
                python-version: '3.10'
            - run: |
                curl -LsSf https://astral.sh/uv/install.sh | sh
                uv pip install --system poetry==1.3.1
                poetry install --all-extras --with dev
            - run: poetry run pytest tests/
